###################################################################################
###################################################################################

# number of simulations to run
Nsims: 30000 

#number of sims to run in parallel
num_parallel: 20 

###################################################################################
###################################################################################

# nside of NILC maps
nside: 128 

# maximum ell for power spectra
ellmax: 250 

# number of ell-space bins
Nbins: 10 

# amplification factor for tSZ map
tSZ_amp: 150. 

# Set to True to use Gaussian tSZ realizations
# (not recommended, use only for testing)
# If False, uses standard non-Gaussian tSZ realizations
use_Gaussian_tSZ: False 

# noise level in uK arcmin
noise: 2500 

# frequencies for maps, in GHz
freqs: [90., 150., 220.] 

# number of needlet filter scales
Nscales: 4 

# array of FWHM used for constrution of Gaussians 
# (needlet filters are differences of two Gaussians). 
# FWHM need to be in strictly decreasing order.
GN_FWHM_arcmin: [300., 120., 60.] 


###################################################################################
###################################################################################

# Set to True to use likelihood-free inference (recommended)
# If set to False, will use analytic Gaussian likelihood, which is only accurate if 
# use_Gaussian_tSZ is True
use_lfi: True

# Half widths of prior to use for LFI
# The prior will be set to [1.0-prior_half_width, 1.0+prior_half_width]
# Only need to be provided if use_lfi is True; otherwise this input is ignored
# Should be list of 2 elements (prior half-widths for Acmb, Atsz)
prior_half_widths: [0.085, 0.8]

# Whether to tune hyperparameters in likelihood-free inference.
# If use_lfi is False, this input is ignored if provided.
# Set to True to use wandb to tune hyperparameters. 
# (See note in README about setting up and logging into wandb before 
# running the program. In this case, the wandb_project_name variable must be provided.)
# Set to False to manually set hyperparameters in the section below.
tune_hyperparameters: False


###################################################################################
###################################################################################
# For each of the parameters in this section, if tune_hyperparameters is True,
# the input is ignored if provided. Otherwise, a default value that has been tuned
# for the settings in this yaml is provided, but these can be changed.

# Learning rate for masked autoregressive flow. 
learning_rate: 2.e-4

# Number of epochs to wait for improvement on the validation set before terminating training.
stop_after_epochs: 40

# Value at which to clip the total gradient norm in order to
# prevent exploding gradients. Use None for no clipping.
clip_max_norm: 5.0

# Number of transforms in the normalizing flow.
num_transforms: 5

# Number of hidden features in the model.
hidden_features: 50

###################################################################################
###################################################################################

# set to True for printing in debug mode (recommended to set to False for long runs)
verbose: False 

# set to True to save pickle files
save_files: True 

# Path to folder containing tSZ maps, assumed to be in Kelvin
halosky_maps_path: '/scratch/09334/ksurrao/NILC/inputs/halosky_maps' 

# File for CMB map in Kelvin, lensed_alm from Websky is in uK
cmb_map_file: '/scratch/09334/ksurrao/NILC/inputs/cmb_lensed_nside1024_K.fits' 

# Path to pyilc code
pyilc_path: '/work2/09334/ksurrao/stampede2/GitHub/pyilc' 

# Path to folder to store outputs
# n.b. see note in README about setting this variable
output_dir: '/scratch/09334/ksurrao/NILC/outputs' 

###################################################################################
###################################################################################
