###################################################################################
###################################################################################

# number of simulations to run
Nsims: 30000 

# number of sims to run in parallel
num_parallel: 20 

###################################################################################
###################################################################################

# nside resolution parameter for generated maps
nside: 128 

# ellmax for power spectra
ellmax: 250 

# number of ell-space bins
Nbins: 10 

# noise level in uK arcmin for each frequency channel
noise: [2500., 2500., 2500.] 

# frequencies for maps, in GHz
freqs: [90., 150., 220.]

# components in the sky model (not including instrumental noise)
# e.g. comps: ['cmb', 'tsz']
comps: ['cmb', 'tsz']

# amplification factor for each component map
# e.g. if the second component is tsz and the second element of amp_factors is 150.,
# the fiducial tsz map will be multiplied by a factor of 150.
amp_factors: [1., 150.]

# List of paths to files or directories containing maps of each component in
# comps list (in the same order). For each component, if the corresponding
# path is a file, the code will use that file to generate several Gaussian 
# realizations with the same power spectrum. If the corresponding path is a 
# directory, the code will search for files in that directory of the form 
# {comp}_00000.fits, {comp}_00001.fits, etc. In this example, the first path should 
# correspond to the first component in comps (cmb). Since it's a file, 
# the code will generate several Gaussian realizations of the power spectrum in the file.
# The second path should correspond to the second component in comps (tsz).
# Since the path provided is a directory, the code will look for 
# tsz_00000.fits, tsz_00001.fits, etc. CMB maps are assumed to be in units of K_CMB.
# All other maps are assumed to have the assumed frequency dependence factored out
# (e.g. tSZ maps should be in dimensionless Compton-y units).
paths_to_comps: [
  '/scratch/09334/ksurrao/NILC/inputs/cmb_lensed_nside1024_K.fits',
  '/scratch/09334/ksurrao/NILC/inputs/halosky_maps'
]

###################################################################################
###################################################################################

# bin width for harmonic ILC frequency-frequency covariance matrix computation, 
# set to 0 for no binning
delta_l: 10 

# Set to True to omit central ell in bin when computing empirical covariance matrix
# for producing harmonic ILC maps (mitigates ILC bias) 
# Set to False to keep central ell in bin
omit_central_ell: False 

# Set to True to compute weights once from "data" and apply to every realization, 
# set to False to compute weights separately for each realization (and include parameter dependence in the weights)
compute_weights_once: True

# Set to True to use likelihood-free inference (recommended)
# If set to False, will use analytic Gaussian likelihood, which is only accurate if 
# use_Gaussian_tSZ is True
use_lfi: True

# Half widths of prior to use for LFI
# The prior will be set to [1.0-prior_half_width, 1.0+prior_half_width]
# Only need to be provided if use_lfi is True; otherwise this input is ignored
# Should be list of Ncomps elements (prior half-widths for each component)
prior_half_widths: [0.085, 0.8]

# Whether to tune hyperparameters in likelihood-free inference.
# If use_lfi is False, this input is ignored if provided.
# Set to True to use wandb to tune hyperparameters. 
# (See note in README about setting up and logging into wandb before 
# running the program. In this case, the wandb_project_name variable must be provided.)
# Set to False to manually set hyperparameters in the section below.
tune_hyperparameters: False


###################################################################################
###################################################################################
# For each of the parameters in this section, if tune_hyperparameters is True,
# the input is ignored if provided. Otherwise, a default value that has been tuned
# for the settings in this yaml is provided, but these can be changed.

# Learning rate for masked autoregressive flow. 
learning_rate: 2.e-4

# Number of epochs to wait for improvement on the validation set before terminating training.
stop_after_epochs: 40

# Value at which to clip the total gradient norm in order to
# prevent exploding gradients. Use None for no clipping.
clip_max_norm: 5.0

# Number of transforms in the normalizing flow.
num_transforms: 5

# Number of hidden features in the model.
hidden_features: 50

###################################################################################
###################################################################################

# set to True for printing in debug mode (recommended to set to False for long runs)
verbose: False 

# Set to True to save pickle files
save_files: True

# Path to folder to store outputs
output_dir: '/scratch/09334/ksurrao/NILC/outputs' 

###################################################################################
###################################################################################
